- modules/ocha_ai_chat/src/Form/OchaAiChatLogsForm.php
- modules/ocha_ai_job_tag/src/Services/OchaAiJobTagTagger.php
Refs: tidying up
Noticed in passing.
> fix: alter unchanged variable name

- modules/ocha_ai_chat/components/chat-form/chat-form.css
- modules/ocha_ai_chat/components/chat-form/chat-form.js
- modules/ocha_ai_chat/components/chat-popup/chat-popup.css
- modules/ocha_ai_chat/components/chat-utils/chat-utils.js
- modules/ocha_ai_chat/src/Form/OchaAiChatChatForm.php
- modules/ocha_ai_chat/src/Form/OchaAiChatLogsForm.php
- modules/ocha_ai_job_tag/ocha_ai_job_tag.module
- modules/ocha_ai_job_tag/src/Plugin/QueueWorker/OchaAiJobTagTaggerWorker.php
- modules/ocha_ai_job_tag/src/Services/OchaAiJobTagTagger.php
- Fixes for AI Chat popup
- Fixes for job tagger
- Coding standards
> Develop -> Main - v1.0.6

- modules/ocha_ai_chat/components/chat-form/chat-form.css
- modules/ocha_ai_chat/components/chat-form/chat-form.js
- modules/ocha_ai_chat/components/chat-popup/chat-popup.css
- modules/ocha_ai_chat/components/chat-utils/chat-utils.js
- modules/ocha_ai_chat/src/Form/OchaAiChatChatForm.php
- modules/ocha_ai_job_tag/ocha_ai_job_tag.module
- modules/ocha_ai_job_tag/src/Plugin/QueueWorker/OchaAiJobTagTaggerWorker.php
Mutation observers that scroll feedback widgets into view when the person expands them, or submits feedback.
Follow-up to #8
> [RW-893] UX followup for feedback toggle/submission

- modules/ocha_ai_chat/components/chat-form/chat-form.css
- modules/ocha_ai_chat/components/chat-form/chat-form.js
- modules/ocha_ai_chat/src/Form/OchaAiChatChatForm.php
- Copy to clipboard feedback matches CD Social Links more closely.
- Hides detailed feedback initially when mode is set to `both`
- Adds a new button to toggle detailed feedback elements
> [RW-928] more UI tweaks

- modules/ocha_ai_tag/ocha_ai_tag.services.yml
- modules/ocha_ai_tag/src/Services/OchaAiTagTagger.php
This uses permanent cache with cache tags for the embeddings
> chore: use cache for embeddings

- modules/ocha_ai_chat/src/Form/OchaAiChatChatForm.php
- modules/ocha_ai_chat/src/Form/OchaAiChatConfigForm.php
- modules/ocha_ai_chat/src/Form/OchaAiChatLogsForm.php
- modules/ocha_ai_chat/src/Plugin/Block/ChatPopup.php
- modules/ocha_ai_chat/src/Services/OchaAiChat.php
- modules/ocha_ai_tag/src/Form/OchaAiTagConfigForm.php
- modules/ocha_ai_tag/src/Services/OchaAiTagTagger.php
- src/Attribute/OchaAiCompletion.php
- src/Attribute/OchaAiEmbedding.php
- src/Attribute/OchaAiSource.php
- src/Attribute/OchaAiTextExtractor.php
- src/Attribute/OchaAiTextSplitter.php
- src/Attribute/OchaAiVectorStore.php
- src/Form/OchaAiConfigForm.php
- src/Plugin/CompletionPluginManager.php
- src/Plugin/EmbeddingPluginManager.php
- src/Plugin/PluginBase.php
- src/Plugin/SourcePluginBase.php
- src/Plugin/SourcePluginManager.php
- src/Plugin/TextExtractorPluginManager.php
- src/Plugin/TextSplitterPluginManager.php
- src/Plugin/VectorStorePluginBase.php
- src/Plugin/VectorStorePluginManager.php
- src/Plugin/ocha_ai/Source/ReliefWeb.php
Refs: #29 
Did a quick functional test and chat still works, all logging still works. Given it's one change across all files, I am hoping that means I didn't break the job tagger or other modules.
I flagged y'all FYI but I will just merge this in if it passes.
> test: PHPCS

- modules/ocha_ai_chat/ocha_ai_chat.routing.yml
- modules/ocha_ai_chat/src/Controller/OchaAiChatController.php
Use a custom access controller, so we can pass a secret in a header and get some piece of software to process these stats for us.
Refs: OPS-10278
> feat: Spit out module use stats as JSON.

- modules/ocha_ai_chat/src/Controller/OchaAiChatController.php
> fix: Do call the access callback, or anyone can access the stats.

- modules/ocha_ai_chat/src/Controller/OchaAiChatController.php
> fix: Ensure the statisticvs access check is called and uses the correct secret.

- modules/ocha_ai_chat/src/Controller/OchaAiChatController.php
> chore: add copied stats

- modules/ocha_ai_chat/src/Controller/OchaAiChatController.php
> Include copied stats

- modules/ocha_ai_tag/src/Services/OchaAiTagTagger.php
Refs: RW-985
This is backward compatible change that allows to provide multiple strings for the term description instead of a single string (ex: several key sentences).
So as it is, this code gives the same results as the current version when using the current term descriptions but it's also possible to pass an array of "strings" for each term which from the tests in RW-985 seems to improve a bit the tagging accuracy.
1. Import a recent DB dump from RW.
2. Clone the repo, checkout the branch and mount the repo directory instead of the contrib ocha_ai **OR** update the RW site composer to use this branch
3. Go to `/admin/config/ocha-ai/tag/config` and ensure the embedding plugin is `aws_bedrock`.
4. Clear the cache
5. Go to the `/moderation/content/job` page and look for a job that was …
> [RW-985] Allow string or array for the term descriptions

- modules/ocha_ai_chat/src/Services/OchaAiChat.php
- modules/ocha_ai_tag/ocha_ai_tag.services.yml
- modules/ocha_ai_tag/src/Form/OchaAiTagConfigForm.php
- modules/ocha_ai_tag/src/Services/OchaAiTagTagger.php
- src/Plugin/SourcePluginInterface.php
- src/Plugin/VectorStorePluginInterface.php
- src/Plugin/ocha_ai/Source/ReliefWeb.php
- src/Plugin/ocha_ai/VectorStore/Elasticsearch.php
- src/Plugin/ocha_ai/VectorStore/ElasticsearchJob.php
> feat: Search using embeddings

- modules/ocha_ai_chat/ocha_ai_chat.routing.yml
Refs: RW-996
Let the permission control access so it can be made available to non logged-in users.
> [RW-996] Remove the user logged in requirements for the chat

- modules/ocha_ai_chat/components/chat-popup/chat-popup.js
- modules/ocha_ai_chat/ocha_ai_chat.module
- modules/ocha_ai_chat/src/Form/OchaAiChatChatForm.php
> chore: change title

- modules/ocha_ai_chat/src/Form/OchaAiChatChatForm.php
> chore: ajax progress message

- modules/ocha_ai_chat/components/chat-form/chat-form.css
Refs: RW-1010
**Before**
**After**
> [RW-1010] Ajax progress message styling

- modules/ocha_ai_chat/components/chat-form/chat-form.css
Refs: RW-1017
Note that I haven't adjusted the positioning of the down arrow in the dropdown element - this is handled by the browser, so would be breaking consistency with other dropdowns.
> chore: adjust padding for ai chat popup

- modules/ocha_ai_chat/components/chat-form/chat-form.css
Refs: RW-1012
Replaces https://github.com/UN-OCHA/ocha_ai/pull/56 with the more versatile solution suggested on that PR.
> chore: style instructions as chat bubbles

- modules/ocha_ai_chat/src/Form/OchaAiChatChatForm.php
> chore: change text for select options

- composer.json
- modules/ocha_ai_chat/src/Form/OchaAiChatChatForm.php
- ocha_ai.info.yml
Refs: RW-1007
Note that the dummy field doesn't show for administrators as they have 'Bypass Honeypot protection' permission. Also needs https://github.com/UN-OCHA/rwint9-site/pull/850
> chore: add honeypot to form

- modules/ocha_ai_chat/src/Form/OchaAiChatChatForm.php
Refs: RW-1007
Fix for https://github.com/UN-OCHA/ocha_ai/pull/49
> fix: ensure honeypot service is properly added to the chat form

- modules/ocha_ai_chat/src/Form/OchaAiChatChatForm.php
> [RW-1019] Fix "only variables should be passed by reference"

- modules/ocha_ai_tag/src/Services/OchaAiTagTagger.php
> feat: Embed using structured data

- modules/ocha_ai_chat/components/chat-form/chat-form.css
> fix: spacing of drupal messages and prevent them from hiding the chat

- config/install/ocha_ai.settings.yml
- config/schema/ocha_ai.schema.yml
- modules/ocha_ai_chat/config/install/ocha_ai_chat.settings.yml
- modules/ocha_ai_chat/src/Services/OchaAiChat.php
- src/Plugin/AnswerValidatorPluginInterface.php
- src/Plugin/RankerPluginInterface.php
- src/Plugin/ocha_ai/AnswerValidator/SimilarityEmbeddingValidator.php
- src/Plugin/ocha_ai/AnswerValidator/SimilarityRankerValidator.php
- src/Plugin/ocha_ai/Ranker/OchaAiHelperRanker.php
Refs: RW-1057
This adds a new answer validator plugin using the reranker from https://github.com/UN-OCHA/ocha_ai_helper/pull/5 and refactor a bit the embedding one.
> [RW-1057] Add similarity ranker answer validator

- src/Plugin/ocha_ai/Completion/AwsBedrockTitanTextPremierV1.php
Missed one in https://github.com/UN-OCHA/ocha_ai/pull/85
> fix: ensure the max_tokens parameter is an integer

- modules/ocha_ai_chat/config/install/ocha_ai_chat.settings.yml
- modules/ocha_ai_chat/config/schema/ocha_ai_chat.schema.yml
- modules/ocha_ai_chat/ocha_ai_chat.services.yml
- modules/ocha_ai_chat/src/Form/OchaAiChatConfigForm.php
- modules/ocha_ai_chat/src/Services/OchaAiChat.php
- tests/src/Unit/TextSplitterOverlapTest.php
- tests/src/Unit/TextSplitterTest.php
Refs: RW-1052
This adds a retrieval mode option for the chat to switch between embeddings and keywords based retrieval of relevant passages.
> [RW-1052] Relevant passage retrieval mode

- modules/ocha_ai_chat/src/Plugin/Block/ChatPopup.php
> [RW-1149] Handle maps in report url check

- modules/ocha_ai_chat/src/Form/OchaAiChatChatForm.php
> [RW-1027] put back the focus to the question field after submitting a question

- modules/ocha_ai_chat/src/Form/OchaAiChatLogsForm.php
- src/Plugin/ocha_ai/Completion/AwsBedrockNovaLiteV1.php
- src/Plugin/ocha_ai/Completion/AwsBedrockNovaMicroV1.php
- src/Plugin/ocha_ai/Completion/AwsBedrockNovaProV1.php
- src/Plugin/ocha_ai/Source/ReliefWeb.php
Refs: OPS-11332
This adds completion plugins for the new AWS Nova models.
It also adds a column in the chat log to display the model and change the source link to point at the document directly when possible.
> [OPS-11332] AWS Nova models

- src/Plugin/ocha_ai/Completion/AwsBedrockNovaV1Base.php
> [RW-1172] Use proper structure for system prompt in nova models

- src/Plugin/CompletionPluginBase.php
- src/Plugin/CompletionPluginInterface.php
- src/Plugin/ocha_ai/Completion/AwsBedrockNovaMicroV1.php
- src/Plugin/ocha_ai/Completion/AwsBedrockNovaV1Base.php
> [RW-1172] Add method to get the list of files that a model supports

- src/Plugin/ocha_ai/Completion/AwsBedrockNovaV1Base.php
> [RW-1210] Use the converse API instead of the invoke API since it supports more document types

- src/Plugin/ocha_ai/Completion/AwsBedrockNovaV1Base.php
> [RW-1220] Convert PDFs to version 1.4 before passing them to Nova models

- modules/ocha_ai_chat/ocha_ai_chat.info.yml
- modules/ocha_ai_tag/ocha_ai_tag.info.yml
- ocha_ai.info.yml
> [OPS-11475] Drupal 11 compatibility
