UN-OCHA/ocha_ai

- config/install/ocha_ai.settings.yml
- config/schema/ocha_ai.schema.yml
- src/Plugin/ocha_ai/VectorStore/Elasticsearch.php
Settings override via:
```
$config['ocha_ai.settings']['plugins']['vector_store']['elasticsearch']['shards'] = 1;
$config['ocha_ai.settings']['plugins']['vector_store']['elasticsearch']['replicas'] = 0;
```
> fix: add settings to indicate the number of shards and replicas to use for the ES indices

- modules/ocha_ai_chat/components/chat-form/chat-form.js
- modules/ocha_ai_job_tag/src/Services/OchaAiJobTagTagger.php
Refs: RW-893
This is to against the [RW-893](https://github.com/UN-OCHA/ocha_ai/tree/RW-893) branch.
Use `?w=1` to more easily see the 3 line changes: https://github.com/UN-OCHA/ocha_ai/pull/9/files?w=1
This wraps the code of the ochaAiChatForm drupal behavior in a `once` to ensure it's executed only once otherwise, the event handlers are added twice. First when the form is loaded and a second time after pressing "ask", which causes new questions to appear twice when pressing "ask" after the first question.
Note: as a rule of thumb, it's safer to wrap the content of a Drupal behavior `attach` method in a [once](https://www.drupal.org/node/3158256) or something [equivalent](https://github.com/UN-OCHA/ocha_ai/blob/f6c9101255c3e95c52eab4da312877c5f374c8c9/modules/ocha_ai_chat/components/chat- …
> [RW-893] Ensure the chat form js is exececuted once

- modules/ocha_ai_chat/components/chat-form/chat-form.css
- modules/ocha_ai_chat/components/chat-form/chat-form.js
- modules/ocha_ai_chat/src/Form/OchaAiChatChatForm.php
⚠️ I unfortunately couldn't debug a major problem before the week ended. PR marked draft. Sorry. ⚠️ 
Now when feedback is submitted, the message that returns looks like a standard Drupal message. The scrolling effect is also disabled for feedback submissions, making it more visible as well.
The show-stopper bug here is that somehow the main submit button will fire N+1 events off after using the feedback mechanism. I tested by submitting feedback more than once, and noted that they always add up to the total number of times you clicked any submit button plus one for the "real" submit button. Here's a screenshot with `console.log` into each function attached to the respective buttons. I took the following actions:
- Press <kbd>Ask</kbd>
- Press <kbd>Submit Feedback</kbd>
- Press …
> [RW-893] Style message when feedback is submitted

- src/Plugin/ocha_ai/TextSplitter/Token.php
This skips the splitting logic if the text is already below the requested token limit.
It also fixes the calculation of the total token count to prevent excessive splitting.
> Fixes for the token text splitter

- modules/ocha_ai_chat/components/chat-form/chat-form.css
- modules/ocha_ai_chat/ocha_ai_chat.install
- modules/ocha_ai_chat/src/Form/OchaAiChatChatForm.php
- modules/ocha_ai_chat/src/Form/OchaAiChatConfigForm.php
- modules/ocha_ai_chat/src/Form/OchaAiChatLogsForm.php
- modules/ocha_ai_chat/src/Services/OchaAiChat.php
Refs: RW-928
- New config option for feedback mode: `both`
- Tweaks to form to allow both feedback modes to co-exist.
- New column on logs table exclusively for thumbs up/down.
- New function inside thumbs up/down callback to store data.
I had some weird trouble with the config form so even though I added very little to the config form, please make sure I didn't screw it up.
> [RW-928] both feedback modes + new column

- modules/ocha_ai_chat/components/chat-form/chat-form.js
- modules/ocha_ai_chat/config/install/ocha_ai_chat.settings.yml
- modules/ocha_ai_chat/config/schema/ocha_ai_chat.schema.yml
- modules/ocha_ai_chat/src/Form/OchaAiChatChatForm.php
- modules/ocha_ai_chat/src/Form/OchaAiChatConfigForm.php
Refs: RW-930
- New `ocha_ai_chat.settings` option: `form.formatting` with default value `basic`
- I put another formatting function into the chat form class. Right now it does the same job as twig filter `nl2br` but I still chose to do it in a function in case we want to add additional processing, or perhaps more granular formatting options in the future.
- Check out branch
- Navigate to OCHA AI Chat config in the Drupal admin, choose "Basic formatting" in the top section.
- Navigate to an Update and ask a question whose answer will require formatting, such as "Give me three talking points"
- The line breaks should be visible in the answer like the screenshot below.
- Copying the answer to clipboard should retain the line breaks.
> feat(ux): better formatting for Chat answers

- modules/ocha_ai_chat/src/Controller/OchaAiChatController.php
Refs: OPS-10278
I had to include the RequestStack to test this locally, so included db connection and logger trait at the same time. I made this PR to stop comments on the other one getting messy.
I also fixed one comment and added some others.
> chore: add comments and fix issues

- src/Plugin/ocha_ai/Embedding/AwsBedrockTitanEmbedTextV2.php
Refs: OPS-10489
This adds a new plugin for the for the AWS titan embed text v2 embedding model.
This is a separate plugin so that it can be used for the job tagging without impacting the chat. 
This model is overall better than the v1 (5-10% increase in accuracy for the job tagging). It's also cheaper and faster.
Note: In the future all the models should probably have their own plugin to be more flexible instead of having one plugin that handles several models.
> [OPS-10489] Add a new embedding plugin for the AWS titan embed text v2

- modules/ocha_ai_chat/components/chat-form/chat-form.js
Refs: RW-1006
Submit the question when pressing enter in the question textarea.
1. Make sure to have the `ocha_ai` use this PR's branch (add `- "../../ocha_ai:/srv/www/html/modules/contrib/ocha_ai:ro"` for example in the local/docker.compose.yml).
2. Clear the cache
3. Open a report on your local RW (do a hard refresh to make sure the `ocha_form.js` is the newest version)
4. Open the chat popup, type a question
5. Still in the textare, press `shift` + `enter` to confirm, you can add a new line
6. Press `enter` and confirm that is submits the question
> [RW-1006] Submit question when pressing enter in the question textarea

- modules/ocha_ai_chat/components/chat-popup/chat-popup.js
- modules/ocha_ai_chat/config/install/ocha_ai_chat.settings.yml
- modules/ocha_ai_chat/config/schema/ocha_ai_chat.schema.yml
- modules/ocha_ai_chat/ocha_ai_chat.routing.yml
- modules/ocha_ai_chat/src/Form/OchaAiChatChatForm.php
- modules/ocha_ai_chat/src/Form/OchaAiChatConfigForm.php
- modules/ocha_ai_chat/src/Plugin/Block/ChatPopup.php
Refs: RW-1020
This adds 2 new settings on the chat form config page to set the chat page title and chat popup title.
1. Ensure you are using this branch
2. Clear the cache
3. Go to `/admin/config/ocha-ai/chat/config`
4. Check the form title and popup title fields are present.
5. Put some values and save
6. Open the AI chat popup and confirm it's using the new title.
> [RW-1020] Allow setting the popup and chat page title via the UI

- modules/ocha_ai_chat/src/Form/OchaAiChatChatForm.php
Refs: RW-1024
This makes sure the answers are sanitized while preserving the basic formatting (line breaks).
There is a bit of leftovers (`formatAnswer` and the formatting settings) but we may want to re-use them if we ever expand on the formatting.
> [RW-1024] Prevent XSS

- modules/ocha_ai_chat/config/install/ocha_ai_chat.settings.yml
- modules/ocha_ai_chat/config/schema/ocha_ai_chat.schema.yml
- modules/ocha_ai_chat/ocha_ai_chat.install
- modules/ocha_ai_chat/src/Form/OchaAiChatChatForm.php
- modules/ocha_ai_chat/src/Form/OchaAiChatConfigForm.php
- modules/ocha_ai_chat/src/Services/OchaAiChat.php
- src/Plugin/CompletionPluginBase.php
- src/Plugin/CompletionPluginInterface.php
- src/Plugin/ocha_ai/Completion/AwsBedrock.php
- src/Plugin/ocha_ai/Completion/AwsBedrockTitanTextPremierV1.php
- src/Plugin/ocha_ai/Completion/AzureOpenAi.php
- src/Plugin/ocha_ai/Source/ReliefWeb.php
- src/Plugin/ocha_ai/VectorStore/Elasticsearch.php
- src/Plugin/ocha_ai/VectorStore/ElasticsearchFlattened.php
Refs: RW-1022
- Add a new completion plugin of the AWS bedrock titan premier model
- Add a new vector store plugin with flattened content to improve accuracy
- Index automatic document description with its embedding to speed up answer generation when no relevant passage found
- Add answer validation by comparing it with relevant passages
- Add settings to set the various default answers + min similarity for answer validation and text splitting setting overrides for accuracy
Note: this is based off https://github.com/UN-OCHA/ocha_ai/pull/60 which should be reviewed and merged first.
> [RW-1022] Reduce jailbreaking

- modules/ocha_ai_chat/ocha_ai_chat.install
- modules/ocha_ai_chat/src/Services/OchaAiChat.php
Refs: RW-1022
- This adds a new field to the chat logs to store an error ID so we can better analyze what happened.
- This also removes unwanted info from the logs and use the standard drupal logging as well. (We'll use the jsonlog module or something to send the log entry to ELK directly.)
> [RW-1022] Better logging

- modules/ocha_ai_chat/src/Form/OchaAiChatChatForm.php
> [RW-1019] Use more specific selector for the ajax commands in chat form

- modules/ocha_ai_chat/src/Controller/OchaAiChatController.php
> fix(security): Throw a 404 not found when access is denied, to avoid disclosing paths.

- modules/ocha_ai_chat/src/Form/OchaAiChatLogsForm.php
Refs: RW-1033
This adds the `original_answer` and `error` columns to the chat logs and change the download format to TSV to ease import since some fields contain commas.
> [RW-1033] Chat logs: more columns and TSV instead of CSV

- modules/ocha_ai_chat/components/chat-form/chat-form.css
- modules/ocha_ai_chat/src/Form/OchaAiChatChatForm.php
Refs: RW-1019
- Coding standards.
- Additional classes to differentiate between the different feedback buttons.
- A bit of refactoring to try to make it clearer what styles what.
> [RW-1019] AI chat feedback icon fix

- modules/ocha_ai_chat/components/chat-form/chat-form.css
- modules/ocha_ai_chat/components/chat-form/chat-form.js
Refs: RW-1047
This refactors the smooth scrolling, using a mutation observer to detect the addition of a question to the chat and when the form is rebuilt after the question submission.
This also fixes the display of the form when an error message (ex: honeypot) is displayed.
> fix: refactor smooth scrolling, handle drupal messages display

- config/schema/ocha_ai.schema.yml
- modules/ocha_ai_chat/src/Form/OchaAiChatLogsForm.php
- src/Plugin/CompletionPluginBase.php
- src/Plugin/ocha_ai/Completion/AwsBedrockTitanTextPremierV1.php
- src/Plugin/ocha_ai/TextSplitter/NLPSentence.php
- src/Plugin/ocha_ai/VectorStore/ElasticsearchFlattened.php
Refs: RW-1044
Add settings to enrich the context  of relevant passages by retrieving adjacent passages.
By default, this is disabled (passages before and after are set to 0) so there is no change to the current behavior.
This also adds a new sentence splitter using the OCHA AI helper: https://github.com/UN-OCHA/ocha_ai_helper. This plugin is completely optional and was used to test context expansion.
> [RW-1044] Context expansion

- config/install/ocha_ai.settings.yml
- config/schema/ocha_ai.schema.yml
- modules/ocha_ai_chat/config/install/ocha_ai_chat.settings.yml
- modules/ocha_ai_chat/config/schema/ocha_ai_chat.schema.yml
- modules/ocha_ai_chat/ocha_ai_chat.services.yml
- modules/ocha_ai_chat/src/Form/OchaAiChatConfigForm.php
- modules/ocha_ai_chat/src/Services/OchaAiChat.php
- ocha_ai.services.yml
- src/Attribute/OchaAiRanker.php
- src/Form/OchaAiConfigForm.php
- src/Plugin/RankerPluginBase.php
- src/Plugin/RankerPluginInterface.php
- src/Plugin/RankerPluginManager.php
- src/Plugin/RankerPluginManagerInterface.php
- src/Plugin/ocha_ai/Ranker/OchaAiHelperRanker.php
Refs: RW-1051
This adds a new "Ranker" plugin type that can be used to rerank results from the vector store.
By default, no ranker is used, so there is no difference with the current behavior.
The provided plugin is meant to be used with a running instance of the OCHA AI helper: https://github.com/UN-OCHA/ocha_ai_helper/pull/1
> [RW-1051] Add ranker plugin type to rerank passages

- config/install/ocha_ai.settings.yml
- config/schema/ocha_ai.schema.yml
- modules/ocha_ai_chat/config/install/ocha_ai_chat.settings.yml
- modules/ocha_ai_chat/config/schema/ocha_ai_chat.schema.yml
- modules/ocha_ai_chat/ocha_ai_chat.services.yml
- modules/ocha_ai_chat/src/Form/OchaAiChatConfigForm.php
- modules/ocha_ai_chat/src/Services/OchaAiChat.php
- ocha_ai.services.yml
- src/Attribute/OchaAiAnswerValidator.php
- src/Form/OchaAiConfigForm.php
- src/Plugin/AnswerValidatorPluginBase.php
- src/Plugin/AnswerValidatorPluginInterface.php
- src/Plugin/AnswerValidatorPluginManager.php
- src/Plugin/AnswerValidatorPluginManagerInterface.php
- src/Plugin/ocha_ai/AnswerValidator/SimilarityValidator.php
- src/Plugin/ocha_ai/Ranker/OchaAiHelperRanker.php
- src/Plugin/ocha_ai/Source/ReliefWeb.php
- src/Plugin/ocha_ai/VectorStore/Elasticsearch.php
Refs: RW-1053
This adds a new `answer validator` plugin type so that we can more easily test different validation strategies.
This starts with a `similarity` plugin that just replaces the validation code that was in the OchaAiChat service.
There are also a few fixes:
- Settings schema adjustments with some missing entries
- Min/max values for the minimum similarity for the ES vector stores
- Indexing of the `body` of the RW documents
**Note**: There shouldn't be any change to the current chat behavior but the `ocha_ai.settings.yml` and `ocha_ai_chat.settings.yml` in the RW repo will need to be adjusted when upgrading to the next version of the `ocha_ai` module.
> [RW-1053] Add answer validator plugin type

- modules/ocha_ai_tag/src/Services/OchaAiTagTagger.php
- src/Plugin/CompletionPluginInterface.php
- src/Plugin/ocha_ai/Completion/AwsBedrock.php
- src/Plugin/ocha_ai/Completion/AwsBedrockTitanTextPremierV1.php
- src/Plugin/ocha_ai/Completion/AzureOpenAi.php
Refs: RW-1109
This adds a generic query method to the completion plugin to be able to use them outside of the chat (ex:  https://github.com/UN-OCHA/ocha_content_classification).
This doesn't change the current functionality and is fully compatible with the chat.
> [RW-1109] Add generic query method to the completion plugin
